### ISSUE TITLE
Starting the flipper

### ISSUE THREAD

**Issue by JJGod1607** [Vikame/SkyblockBINSniper#2]
The error I get is 

java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
        at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
        at me.vikame.binsnipe.BINSniper.getAuctions(BINSniper.java:318)
        at me.vikame.binsnipe.BINSniper.lambda$new$6(BINSniper.java:69)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
        
        My config file is :
        #Skyblock BIN Sniper configuration data
#**This was removed on purpose**
TIMEOUT=10000
SOUND_WHEN_FLIP_FOUND=true
MIN_ITEMS_ON_MARKET=5
MIN_PROFIT_PERCENTAGE=110.0
FORCE_NO_CACHE_API_REQUESTS=false
IGNORE_FURNITURE=true
MIN_BIN_PRICE=2
MAX_BIN_PRICE=2147483647
EXPLICIT_GC_AFTER_FLIP=false
IGNORE_RECOMB=true
MAX_FLIPS_TO_SHOW=10
IGNORE_SKINS=true
IGNORE_REFORGES=true
USE_GZIP_COMPRESSION_ON_API_REQUESTS=true
IGNORE_USED_CAKE_SOULS=true
POOLED_THREAD_COUNT=16
IGNORE_COSMETICS=true
MIN_PROFIT_AMOUNT=800000
OLD_THRESHOLD=180000
IGNORE_HOT_POTATO=true
IGNORE_STARS=true

**Comment by Vikame** [comment]
This seems to have occurred due to an issue connecting to the Hypixel Auctions API. Can you check if you are able to access https://api.hypixel.net/skyblock/auctions?page=0 without issue? Is the error consistent, or random? This may be a case of your fire-wall blocking access to the internet, in which case you would need to add Java to your firewall's whitelist.
